name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm ci

    - name: Build project
      run: pnpm run build

    - name: Test project
      run: pnpm test